### ISSUE TITLE
Can we steal your package name?

### ISSUE THREAD

**Issue by benjamingr** [andreypopp/promised#1]
We're discussing promises in node core now (look at how time passes) and we're considering something like `promised/fs`. That would regrettably break this module. 

Would that be fine with you? We'd really appreciate the gesture.

**Comment by andreypopp** [comment]
chris dickinson also contacted me. Are both yours and his attempt are coordinated between? To whom should I transfer ownership?

**Comment by benjamingr** [comment]
To him (to the Node organization, really) :)

**Comment by benjamingr** [comment]
Also - yes, this is where they are coordinated https://github.com/nodejs/promises

**Comment by andreypopp** [comment]
@benjamingr ok, what's the username? https://www.npmjs.com/~nodejs ?

**Comment by andreypopp** [comment]
Done.

**Comment by benjamingr** [comment]
Thanks :)
